version: "3.2"

services:
  single_spa_root:
    build: ./
    ports:
      - 9000:9000

  opr_epr_tracker:
    build: OPR_EPR_TRACKER
    ports:
      - 9002:9002

  main_page:
    build: Main_Page
    ports:
      - 9001:9001

  inbound_outbound_tracker:
    build: Inbound_Outbound_Tracker
    ports:
      - 9003:9003

  additional_duty_tracker:
    build: Additional_Duty_Tracker
    ports:
      - 9004:9004

  users-db:
    build: _Database
    image: mysql:8
    ports:
      - "3309:3306"
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

      - users-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: personneltrackerdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  users-data:
    driver: local